module.exports = [
    {
        "id": "CYI18MKL4SY",
        "type": "Accessories",
        "name": "KICO Baby Wool Beige",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Slofjesaan_990x.jpg?v=1648653328",
        "Price": "€33",
        "stock": 20,
        "description": "Your little one will not have cold feet with these lovely slippers. They are made of 100% merino wool, which is breathable. You can tie the cord so that the slippers stay on well.",
        "brand": "KICO",
        "DateAdded": "08-04-2022",
        "Material": "100% wool",
        "availableSizes": [
            1,
            2,
            3
        ]
    },
    {
        "id": "OZR29HLV4XM",
        "type": "Accessories",
        "name": "BABYZUS Pacifier Clip Natural Wood",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Speenkoordleopardsalmon_990x.jpg?v=1647726822",
        "Price": "€20",
        "stock": 2,
        "description": "With a pacifier cord you no longer have to worry about pacifiers that continuously fall to the floor. This beautiful piece from Babyzus has a nice quality satin cord, BPA-free silicone beads and a wooden clip. It is handmade and meets European safety standards.",
        "brand": "BABYZUS",
        "DateAdded": "06-04-2022",
        "Material": "Natural wood"
    },
    {
        "id": "XMJ46USH2EM",
        "type": "Toys",
        "name": "MYLITTLE Kawan Teether Set Sandy Nude",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Kawantoygiftsetsandynude_990x.jpg?v=1648654318",
        "Price": "€16",
        "stock": 9,
        "description": "When your baby suffers from teething, teething toys  are very  nice. This set consists of the Kawan teething ring and a separate ring. Both are made of 100% natural rubber and  free from BPA, PVC, plastic and phthalates. Only vegetable pigments are used for the colors. There are no openings, which prevents bacteria from getting in between. For this reason it is also easy to clean and hygienic. It is a safe toy that also looks nice and is easy to hold by the smallest hands.",
        "brand": "MYLITTLE",
        "DateAdded": "07-04-2022",
        "Material": "100% natural rubber"
    },
    {
        "id": "EJJ49SGU7LH",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket Deep Beige",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenbamboedeepbeige_990x.jpg?v=1648416279",
        "Price": "€40",
        "stock": 1,
        "description": "A wonderfully comfortable blanket made of bamboo and cotton with a beautiful knitted design. Use it in the crib, on the road or in the playpen. The material is airy and light. Ideal to use in summer, but also suitable for winter. Bamboo is also hypoallergenic, so great for sensitive baby skin.",
        "brand": "MINUMINI",
        "DateAdded": "15-11-2020",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 80,
        "height": 100,
    },
    {
        "id": "ALP31IPT3CI",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket Peach Dust",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenbamboepeachdust_990x.jpg?v=1648417158",
        "Price": "€20",
        "stock": 0,
        "description": "A nice soft blanket made of bamboo and cotton. Use it in the crib, on the road or in the playpen. The material is airy and light. Ideal to use in summer, but also suitable for winter. Bamboo is also hypoallergenic, so great for sensitive baby skin.",
        "brand": "MINUMINI",
        "DateAdded": "26-11-2020",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 80,
        "height": 100,
    },
    {
        "id": "NOO77BMR4QN",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket Creamy Smoke",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenbamboecreamysmoke_990x.jpg?v=1648416610",
        "Price": "€50",
        "stock": 9,
        "description": "A nice soft blanket made of linen and cotton. Use it in the crib, on the go, in the playpen or even as a bath towel. Handmade with a nice puffy waffle structure. The material is soft, airy and light. Ideal to use in summer, but also suitable for winter. It keeps your child pleasantly warm.",
        "brand": "MINUMINI",
        "DateAdded": "15-11-2020",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 100,
        "height": 100,
    },
    {
        "id": "MXN88PIQ8QL",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket white",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenbamboeoffwhite_990x.jpg?v=1648415606",
        "Price": "€30",
        "stock": 9,
        "description": "A wonderfully comfortable blanket made of bamboo and cotton with a beautiful knitted design. Use it in the crib, on the road or in the playpen. The material is airy and light. Ideal to use in summer, but also suitable for winter. Bamboo is also hypoallergenic, so great for sensitive baby skin.",
        "brand": "MINUMINI",
        "DateAdded": "22-12-2021",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 80,
        "height": 100,
    },
    {
        "id": "VRQ36FGG6LO",
        "type": "Blanket",
        "name": "MINUMINI Blanket Sand",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenlinnensand_990x.jpg?v=1648414504",
        "Price": "€80",
        "stock": 17,
        "description": "A lovely soft blanket made of 100% wool in the color beige with a circle boucle design. Wool breathes and does not sweat, so your little one stays at body temperature. This blanket has a double layer, so it keeps your baby nice and warm.",
        "brand": "MINUMINI",
        "DateAdded": "04-05-2021",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 100,
        "height": 100,
    },
    {
        "id": "TLQ47XPB8OB",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket Creamy Smoke",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Dekenbamboecreamysmoke_990x.jpg?v=1648416610",
        "Price": "€60",
        "stock": 45,
        "description": "A nice soft blanket made of bamboo and cotton. Use it in the crib, on the road or in the playpen. The material is airy and light. Ideal to use in summer, but also suitable for winter. Bamboo is also hypoallergenic, so great for sensitive baby skin.",
        "brand": "MINUMINI",
        "DateAdded": "29-08-2021",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 100,
        "height": 100,
    },
    {
        "id": "NLR44PGM7XF",
        "type": "Blanket",
        "name": "MINUMINI Bamboo Blanket Creamy Sage",
        "image": "https://minumini.nl/wp-content/uploads/2020/10/gebreide-baby-deken.jpg",
        "Price": "€30",
        "stock": 0,
        "description": "A nice soft blanket made of bamboo and cotton. Use it in the crib, on the road or in the playpen. The material is airy and light. Ideal to use in summer, but also suitable for winter. Bamboo is also hypoallergenic, so great for sensitive baby skin.",
        "brand": "MINUMINI",
        "DateAdded": "15-04-2020",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 80,
        "height": 100,
    },
    {
        "id": "NSB05IXQ7KC",
        "type": "Books",
        "name": "Minne & Mine Growing up book 0-4 years",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/0-4boekkaft_990x.jpg?v=1648247674",
        "Price": "€60.99",
        "stock": 0,
        "description": "A fill-in book to record everything from your pregnancy up to and including the fourth year of your baby. The book has a beautiful red cover and has no less than 200 pages. Make beautiful and special memories and record them in this book. Also there is plenty of room to add photos. Nice to read it back later and/or give it to your child.",
        "brand": "MYLITTLE",
        "DateAdded": "15-07-2020",
    },
    {
        "id": "VML25HOA7DM",
        "type": "Books",
        "name": "Great Adventures",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/groteavondturen.jpg?v=1648895253",
        "Price": "€80",
        "stock": 73,
        "description": "Journey of a little cat with her family.",
        "brand": "MYLITTLE",
        "DateAdded": "15-02-2021",
        "Material": "50% bamboo fibers and 50% cotton",
        "width": 100,
        "height": 100,
    },
    {
        "id": "RVP83LEK6CW",
        "type": "Accessories",
        "name": "Moon Pillow XL Sand",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/MaankussenXLsand_990x.jpg?v=1647721369",
        "Price": "€80",
        "stock": 2,
        "description": "The cotton moon pillow XL from Play at Slaep has a playful soft pom on the tip of the moon. It is filled with organic kapok, which is hypoallergenic and self-cleaning.",
        "brand": "KICO",
        "DateAdded": "15-07-2020",
        "Material": "100% cotton",
    },
    {
        "id": "WIM44DQO0KH",
        "type": "Accessories",
        "name": "Sleep Moon Pillow XL Latte",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/MaankussenXLlatte_990x.jpg?v=1647721257",
        "Price": "€30.99",
        "stock": 7,
        "description": "The cotton moon pillow XL from Play at Slaep has a playful soft pom on the tip of the moon. It is filled with organic kapok, which is hypoallergenic and self-cleaning.",
        "brand": "KICO",
        "DateAdded": "15-05-2021",
        "Material": "100% cotton",
    },
    {
        "id": "PKC33QTH2XB",
        "type": "Accessories",
        "name": "Moon Pillow Sand",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Maankussensandpackshot_990x.jpg?v=1647721512",
        "Price": "€60",
        "stock": 8,
        "description": "The cotton moon pillow XL from Play at Slaep has a playful soft pom on the tip of the moon. It is filled with organic kapok, which is hypoallergenic and self-cleaning.",
        "brand": "KICO",
        "DateAdded": "15-11-2021",
        "Material": "100% cotton",
    },
    {
        "id": "TYZ25DJJ5VP",
        "type": "Accessories",
        "name": "Moon Pillow Sugar",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Maankussensugarpackshot_990x.jpg?v=1647721557",
        "Price": "€80",
        "stock": 47,
        "description": "The cotton moon pillow XL from Play at Slaep has a playful soft pom on the tip of the moon. It is filled with organic kapok, which is hypoallergenic and self-cleaning.",
        "brand": "KICO",
        "DateAdded": "07-01-2022",
        "Material": "100% cotton",
    },
    {
        "id": "CGT96TEI2WO",
        "type": "Blanket",
        "name": "Garbo and Friends Royal",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Hoeslakenroyalcress_990x.jpg?v=1649180044",
        "Price": "€80",
        "stock": 36,
        "description": "A blanket with a beautiful 'Royal Cress' design made of top quality cotton.",
        "brand": "MINUMINI",
        "DateAdded": "15-06-2021",
        "Material": "100% cotton",
        "width": 60.99,
        "height": 120,
    },
    {
        "id": "VPY67AWR8KD",
        "type": "Blanket",
        "name": "Kico Label Sand",
        "image": "https://cdn.shopify.com/s/files/1/0626/7224/0853/products/Hoeslakensandpackshot_990x.png?v=1647701702",
        "Price": "€14.95",
        "stock": 57,
        "description": "A lovely soft blanket made of 100% muslin cotton in the color pecan. The fabric is breathable, anti-allergic and very comfortable.",
        "brand": "KICO",
        "DateAdded": "15-04-2021",
        "Material": "100% cotton",
        "width": 100,
        "height": 100,
    },
    {
        "id": "AQI96FST1GJ",
        "type": "Accessories",
        "name": "Silicone Bib",
        "image": "https://garboandfriends.centracdn.net/client/dynamic/images/516_67c2f00f0e-mh5390315-0280-sc_full.jpg",
        "Price": "€18",
        "stock": 24,
        "description": "Keep your little one feeling comfy and clean with Mushies fun-loving collection of silicone bibs.",
        "brand": "MINUMINI",
        "DateAdded": "5-11-2020",
        "Material": "Grade Silicone"
    },
    {
        "id": "WWU26FPG7NU",
        "type": "Accessories",
        "name": "Bunny Teething Ring",
        "image": "https://garboandfriends.centracdn.net/client/dynamic/images/524_5a60fa1005-teething_ring_bunny_sand-sc_full.jpg",
        "Price": "€36",
        "stock": 10,
        "description": "To relieve baby's sore gums during the teething phase, Main Sauvage imagined this elegant and simple puppy teether.",
        "brand": "MINUMINI",
        "DateAdded": "13-03-2022",
        "Material": "100% Baby alpaca wool"
    },
    {
        "id": "OSE88OFX0HM",
        "type": "Blanket",
        "name": "Bluebell Royal",
        "image": "https://garboandfriends.centracdn.net/client/dynamic/images/707_32a257fcc0-gf12022-1600-sc_full.jpg",
        "Price": "€100",
        "stock": 4,
        "description": "This blanket is made in cotton muslin that is tightly woven with the finest yarn, making it beautifully textured, heavenly soft and lightweight as well as durable. ",
        "brand": "MINUMINI",
        "DateAdded": "26-11-2020",
        "Material": "100% cotton",
        "width": 100,
        "height": 100
    },
    {
        "id": "SCU12AAL6NI",
        "type": "Accessories",
        "name": "Jersey Triangle Bib",
        "image": "https://garboandfriends.centracdn.net/client/dynamic/images/513_2691b936ef-gf73921212-2100-1-sc_full.jpg",
        "Price": "€20",
        "stock": 5,
        "description": "Silky-soft Triangle Bib both protects and completes your little baby's outfit. The bib is made in 100% Cotton Jersey with silk-finish for that extra softness and features two nickel-free snap buttons in the back for size adjustment.",
        "brand": "MYLITTLE",
        "DateAdded": "29-08-2021",
        "Material": "100% cotton"
    }
]